### ISSUE TITLE
ImportError: FaceDetectionPipeline: DamoFdDetect: cannot import name 'Config' from 'mmcv' (unknown location)

### ISSUE THREAD

**Issue by shengzewen** [modelscope/facechain#77]
![image](https://github.com/modelscope/facechain/assets/48091887/dbc72cc5-c930-4721-8ecd-12289b93a3c2)
开始训练后报这个错，我装了mvcc-full 1.7.0的版本

**Comment by xiaohaipeng** [comment]
install both mmcv and mmcv--full ,should fix it

**Comment by chenluyuZZ** [comment]
It's still not working for me. I installed mmcv =2.1 and mMCV-full =1.7.2 for my torch
